### ISSUE TITLE
I need help finding where the update suppressor file is so I can update my 2ds

### ISSUE THREAD

**Issue by btl200** [GiantBlargg/UpdateSuppressor#1]
Please get back to me asap I need to update my 2ds and I don’t know where the files are kept for the nag suppressor so I need some help

**Comment by GiantBlargg** [comment]
This app only suppresses the update nag for individual apps, if you need to update a previously suppressed app you should be able to do so from the eshop. This app does not prevent system updates, so you can update as normal from the system settings. That being said you probably shouldn't be using this app anymore, it was useful when we had to use ironfall to launch homebrew but with newer methods it shouldn't be necessary anymore.
